version: "3.2"
networks:
  netops-axe:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24

services:
  netaxe-server:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-backend:1.0.12
    container_name: netaxe-server
    ports:
      - "8001:8001"
      - "5555:5555"
    # command: sleep 999999
    command: sh start.sh web
    depends_on:
      - redis-cache
    volumes:
      - ../../netaxe:/home/netaxe
      - ./logs/netaxe_log:/home/netaxe/logs
    networks:
      - netops-axe

  netaxe-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/nginx:1.7.9
    container_name: netaxe-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../../netaxe:/home/netaxe
    ports:
      - "9999:9999"
    depends_on:
      - netaxe-server
    networks:
      - netops-axe

  netaxe-web:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-web:1.0.4
    build: 
      context: ../../web
    container_name: netaxe-web
    ports:
      - "8888:80"
    depends_on:
      - netaxe-nginx
      - netaxe-server
    networks:
      - netops-axe
      
  celery-default:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-backend:1.0.12
    container_name: celery-default
    command: sh start.sh default
    depends_on:
      - redis-cache
      - netaxe-server
    volumes:
      - ../../netaxe:/home/netaxe
    networks:
      - netops-axe
      
  celery-ipam:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-backend:1.0.12
    container_name: celery-ipam
    command: sh start.sh ipam
    depends_on:
      - redis-cache
      - netaxe-server
    volumes:
      - ../../netaxe:/home/netaxe
    networks:
      - netops-axe

  celery-config:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-backend:1.0.12
    container_name: celery-config
    command: sh start.sh config
    depends_on:
      - redis-cache
      - netaxe-server
    volumes:
      - ../../netaxe:/home/netaxe
    networks:
      - netops-axe

  redis-cache:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    # command: sleep 999999 
    command: "redis-server --requirepass dade0f2a65237a56b79277e6dd27351d2854df033e0ad4b4f90abec229cd64df"
    networks:
      - netops-axe

  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/nacos-server:2.0.3
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      #模式为单体模式
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - netops-axe

  apisix-dashboard:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/apisix-dashboard:2.13-alpine
    container_name: apisix-dashboard
    restart: always
    volumes:
      - ./conf/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9948:9000"
    networks:
      - netops-axe

  apisix:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/apisix:2.15.0-alpine
    container_name: apisix
    restart: always
    volumes:
      - ./logs/apisix_log:/usr/local/apisix/logs
      - ./conf/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      - netops-axe
