version: "3.2"
networks:
  netops-databases:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.13.0/24
services:
  mysql-server:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/mysql:5.7
    restart: always
    container_name: mysql-server
    environment:
      TZ: Asia/Shanghai
      MYSQL_USER: "netaxe"
      MYSQL_DATABASE: "netaxe"
      MYSQL_ROOT_PASSWORD: "root_devnet@2022"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "3306:3306"
    networks:
      - netops-databases

  mongodb:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: netaxe
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 70uUceCVL1gf
    volumes:
      - /etc/localtime:/etc/localtime
      - /data/mongo/db:/data/db
      - ./mongodb.conf:/data/conf
      - ./init/:/docker-entrypoint-initdb.d/
    security_opt:
      - 'seccomp=unconfined'
    command: mongod
    networks:
      - netops-databases

  mongo-express:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 70uUceCVL1gf
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 70uUceCVL1gf
    networks:
      - netops-databases

  etcd:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/etcd:3.4.15
    container_name: etcd
    restart: always
    volumes:
      - ./etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - netops-databases