version: "3.2"
networks:
  docker_netaxe:
    external: true

services:
  alertgateway-backend:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/alertgateway-backend:1.0
    container_name: alertgateway-backend
    restart: always
    command: uvicorn controller:app --host 0.0.0.0 --port 8000
    ports:
      - "31102:8000"
    volumes:
      - ./config.json:/app/config/config.json
    networks:
      - docker_netaxe

  alertgateway-worker:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/alertgateway-backend:1.0
    container_name: alertgateway-worker
    restart: always
    command: python3 worker.py default
    volumes:
      - ./config.json:/app/config/config.json
    networks:
      - docker_netaxe

  alertgateway-web:
    container_name: alertgateway-web
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/alertgateway-web:1.0
    ports:
      - "32202:80"
    restart: always
    networks:
      - docker_netaxe