version: "3.2"
networks:
  docker_netaxe:
    external: true
    
services:
  base-backend:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-backend:1.0
    container_name: base-backend
    ports:
      - "5555:5555"
    command: sh init.sh
    volumes:
      - ./config.json:/config/config.json
      - ./defaults.json:/config/defaults.json
      - ./logs:/app/logs
    networks:
      - docker_netaxe

  base-nginx:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-nginx:1.23.1
    container_name: base-nginx
    ports:
      - "31100:80"
    depends_on:
      - base-backend
    networks:
      - docker_netaxe

  base-web:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-web:1.0
    container_name: base-web
    ports:
      - "32200:80"
    depends_on:
      - base-nginx
      - base-backend
    networks:
      - docker_netaxe
      
  celery-default:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-backend:1.0
    container_name: celery-default
    command: sh start.sh default
    depends_on:
      - base-backend
    volumes:
       - ./config.json:/config/config.json
       - ./defaults.json:/config/defaults.json
    networks:
      - docker_netaxe

  celery-config:
    image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-backend:1.0
    container_name: celery-config
    command: sh start.sh config
    volumes:
      - ./config.json:/config/config.json
      - ./defaults.json:/config/defaults.json
    depends_on:
      - base-backend
    networks:
      - docker_netaxe
  